$background = 0f0e08
$onBackground = ebe5d2
$surface = 0f0e08
$surfaceDim = 0f0e08
$surfaceBright = 2f2c1f
$surfaceContainerLowest = 000000
$surfaceContainerLow = 15130b
$surfaceContainer = 1b1a10
$surfaceContainerHigh = 222015
$surfaceContainerHighest = 282619
$onSurface = ebe5d2
$surfaceVariant = 282619
$onSurfaceVariant = b0ab99
$outline = 797665
$outlineVariant = 4b483a
$inverseSurface = fef9ed
$inverseOnSurface = 57554c
$shadow = 000000
$scrim = 000000
$surfaceTint = d2c88a
$primary = d2c88a
$primaryDim = c4ba7e
$onPrimary = 474111
$primaryContainer = 5a5322
$onPrimaryContainer = efe5a5
$inversePrimary = 67602d
$primaryFixed = eee4a4
$primaryFixedDim = e0d697
$onPrimaryFixed = 464010
$onPrimaryFixedVariant = 635c2a
$secondary = cec7a2
$secondaryDim = c0b995
$onSecondary = 454125
$secondaryContainer = 403c21
$onSecondaryContainer = c7c09c
$secondaryFixed = ebe3bd
$secondaryFixedDim = ddd5b0
$onSecondaryFixed = 444024
$onSecondaryFixedVariant = 615c3e
$tertiary = ffddb7
$tertiaryDim = fdcc91
$onTertiary = 6d4b1c
$tertiaryContainer = fdcc91
$onTertiaryContainer = 634214
$tertiaryFixed = fdcc91
$tertiaryFixedDim = eebe85
$onTertiaryFixed = 4d3003
$onTertiaryFixedVariant = 6e4c1d
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = 807842
$secondaryPaletteKeyColor = 7d7858
$tertiaryPaletteKeyColor = 97703e
$neutralPaletteKeyColor = 7a776e
$neutralVariantPaletteKeyColor = 7b7767
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = 807842
$secondary_paletteKeyColor = 7d7858
$tertiary_paletteKeyColor = 97703e
$neutral_paletteKeyColor = 7a776e
$neutral_variant_paletteKeyColor = 7b7767
$term0 = 353433
$term1 = b58b00
$term2 = ddce4c
$term3 = ffe577
$term4 = a3b173
$term5 = d4a243
$term6 = ccce78
$term7 = e0d8bf
$term8 = a9a290
$term9 = d2a200
$term10 = f0e044
$term11 = fff4ce
$term12 = c0c499
$term13 = e3b967
$term14 = e1e07e
$term15 = ffffff
$rosewater = fbf0e0
$flamingo = f2e0c0
$pink = ffd79d
$mauve = ffad7f
$red = e0ac3c
$maroon = deb970
$peach = e6cc7f
$yellow = fef1bd
$green = e4e581
$teal = dae798
$sky = cee494
$sapphire = b3d27e
$blue = 75cf9d
$lavender = 89dcc6
$klink = 559652
$klinkSelection = 559652
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = ac8100
$knegativeSelection = ac8100
$kneutral = cea600
$kneutralSelection = cea600
$kpositive = aab009
$kpositiveSelection = aab009
$text = ebe5d2
$subtext1 = b0ab99
$subtext0 = 797665
$overlay2 = 6a6758
$overlay1 = 5a584a
$overlay0 = 4b493d
$surface2 = 3d3b31
$surface1 = 2f2d24
$surface0 = 1f1d16
$base = 0f0e08
$mantle = 0f0e08
$crust = 0e0d08
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
